markdown: rdiscount 
permalink: /:year/:month/:day/:title 
name: 等待那一刻
title: Kivdy Blog
url: http://Kivdy.com
exclude: [ README.md, newpost.rb ]
domain: kivdy.com
author: Kivdy
email: gfanghao@gmail.com
auto: true
disqusShortname: kivdy