markdown: rdiscount 
permalink: /:year/:month/:day/:title 
title: Kivdy Blog
url: http://Kivdy.com
exclude: [ README.md, newpost.rb ]
domain: kivdy.com
author: gcfanghao
email: gfanghao@gmail.com
auto: true
disqusShortname: kivdy